DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS GROUP;

CREATE TABLE USER 
(
    ID INT PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR(450),
);

CREATE TABLE GROUP
(
    ID  INT PRIMARY KEY NOT NULL,
    ADMIN INT, 
    MEMBERS ARRAY(int),
    CONSTRAINT FK_GROUP_admin_ID FOREIGN KEY (ADMIN) REFERENCES USER(ID),

);
